### ISSUE TITLE
Availablilty of parts and additional D+/- GND/VIN

### ISSUE THREAD

**Issue by RoelStierum** [maasijam/model_d_controller#2]
Dear Maasijam,

Many thanks for posting the code and materials listing to build a controller for the Moog Model D app. Your generosity is really appreciated. Together with my dad, who is actually the one who is planning to use the controller, we plan to make this a joint summer holiday project, in case we are still homebound because of COVID-19. We have a few questions and hope you are willing and can help us:
1)	Some of the materials appear to be out of order from the websites you have indicated. As the specs are not always clearly indicated on these websites, do you know of any alternative suppliers than can provide the following parts? I've found some alternatives but i do not know if they are compatible, could you also be so kind to take a look at those parts?

_Unavailable parts_
B5K D Shaft Alpha 9mm | 3 | https://www.thonk.co.uk/shop/alpha-9mm-pots-dshaft/
Toggleswitch SPDT | 10 | https://www.musikding.de/Toggleswitch-SPDT
Red Push Button Befaco | 5 | https://www.thonk.co.uk/shop/befaco-parts/

_Alternative parts_
Toggleswitch - https://www.aliexpress.com/item/33033085981.html?spm=a2g0o.productlist.0.0.44de6ff7wbqOr7&algo_pvid=33ee826d-a80b-4e50-bbb3-7b087640e3e4&algo_expid=33ee826d-a80b-4e50-bbb3-7b087640e3e4-10&btsid=0b0a3f8115893087539801107eea53&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

Red push button befaco - https://www.aliexpress.com/item/32711341102.html?spm=a2g0o.productlist.0.0.14e65e5a1POC43&algo_pvid=60f6002b-42f3-44b5-b914-57e93d484c3d&algo_expid=60f6002b-42f3-44b5-b914-57e93d484c3d-9&btsid=0b0a3f8115893091890034804eea53&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

2)	On the Gerber PCB files there seems to be an additional D+/D- GND/VIN, so not were the USB socket will be: is this for an additional power supply, e.g. to not drain power from the iPad? These connections are located next to the teensy board.
![moogpcb](https://user-images.githubusercontent.com/60602417/81807596-ab141900-951e-11ea-954d-bf3322667479.png)

3)	I assume the controller can be combined with a piano type key bed using a midi hub?

4)	Once we get going, and stumble upon questions, would you be willing to share further experiences if needed?

Many thanks, stay healthy! By the way we enjoyed very much the nice minimoog synth sounds from your youtube channel!

Best regards,

Roel and Rob

**Comment by maasijam** [comment]
Hi,
glad you like my controller.
I just uploaded an assembly guide. I hope that makes everything a little more understandable.

The alternative parts for the switches and buttons look correct.
As an alternative to the d-Shaft Alpha you could take them here:
https://www.musikding.de/Poti-9mm-5k-lin-Print-vertikal
But they are not d-shaft, so you need other knobs.
You could also take 10K pots. It's only important that they are linear.

Yes, you can combine the controller with other midi devices via usb hub.

Feel free to ask if you have problems. When I have the time I will try to answer.
Best regards
tom

**Comment by robmoog** [comment]
Dear Maasijam,

We have assembled the model D controller and it all works great!! Many many thanks for helping to bring the Minimoog app much more alive, I will use the controller frequently in my band! 

One suggestion from our site for  the assembly guide may be to add in step 4 and step 5 also some text describing the two additional wire connections  needed soldering (GND, VN), b. And for the components list on the led perhaps to mention that 75 mcd is sufficient, but perhaps to the more experienced developer all of this is obvious, then never mind.

Finally the controller has some additional knobs that I couldn't midi map straight away within the Minimoog app (on/delay, on/sync, time, feedback and mix). Are these for communication to an additional app running in the background (e.g. for looping?) , e.g. via AUM?

Cheers Rob

**Comment by maasijam** [comment]
Hi Rob,

great to hear that you successfully assembled the controller.
Thanks for the suggestions for the assemby guide, but you don't have to solder additional wires to the GND/VIN pins. These pins are completly useless, and I will remove them in the next version. But maybe I didn't understand you correctly.

The additional knobs (on/delay, on/sync, time, feedback and mix) are for controlling the delay effect of the model-d app. If you use the moog model-d app you can find  the delay under the "EFFECTS" tab.

Best regards
Tom

**Comment by robmoog** [comment]
Dear Tom

Just wanted to share a picture of a casing I made of your controller! Still brings so much fun to my music making. Cheers Rob



Verstuurd vanaf mijn iPhone

**Comment by maasijam** [comment]
Hi Rob,

I can't see your picture! Maybe because the issue is closed?

Best regards 
Tom


> Dear Tom Just wanted to share a picture of a casing I made of your controller! Still brings so much fun to my music making. Cheers Rob

**Comment by robmoog** [comment]
![623F81F1-53B6-4C05-A4A6-9CE5420EEF35](https://user-images.githubusercontent.com/68874884/127962756-e69ef02e-0a8f-4aee-8d41-136e068fa263.jpeg)

**Comment by robmoog** [comment]
Dear Tom, I added it from the github environment, hope you can see it, cheers Rob

Verstuurd vanaf mijn iPhone

**Comment by maasijam** [comment]
Wow, that looks awesome. Thanks for sharing this picture.
Best regards
Tom

**Comment by gallivas** [comment]
I'm so excited to try my hand at building one of these. Thank you Maasijam for putting all this documentation together. I recently subscribed to your YouTube channel after seeing one of your Model D jams.

I was wondering if you would recommend the [Teensy 4.0](https://www.pjrc.com/store/teensy40.html) at this point as opposed to the LC considering the LC is no longer made. I'm new to building this sort of thing, so I'm curious if using the 4.0 instead will cause any issues.

Also, I compiled a list of US suppliers for components that you may wish to reference for any of your US-based subscribers looking to build this. I've attached it below. If you have a moment, I'd be curious to know if any of the components I linked are incorrect for this build. I tried to find the most similar products I could.

[BOM_maasijam_modeld_controller.csv](https://github.com/maasijam/model_d_controller/files/12386332/BOM_maasijam_modeld_controller.csv)

**Comment by maasijam** [comment]
Hi,
with a little hack the Teensy 4 should work. You have to use the onboard micro usb connector for the d+/d- pins.

![IMG_20230820_111440122](https://github.com/maasijam/model_d_controller/assets/50107149/8aa56a6b-eab5-4443-8862-0e94bd0fe510)

And thanks for the modified BOM - I will exchange it.

Best regards
Tom
